module.exports = {
    formHead:{
        fontSize:35,
        color: "black",
        textAlign:"center",
        fontWeight: "800",
        // backgroundColor:"white",

    },
    formInput:{
        width: "80%",
        // height: 40,
        // backgroundColor:"gray",
        borderRadius:10,
        marginVertical: 10,
        paddingHorizontal: 15,
        paddingVertical: 10,
        fontSize : 18,
        borderColor:"black",
        borderWidth:2,
    },
    formbtn:{
        width: "80%",
        backgroundColor: "#ffa31a",
        borderRadius: 20,
        borderColor: "#ffa31a",
        borderWidth: 1,
        fontSize: 20,
        color: "white",
        textAlign: "center",
        paddingVertical: 10,
        marginVertical:10,
    },
    formTextLinkRight: {
        color: "grey",
        fontSize: 15,
        textAlign: "right",
        width: "80%",
        marginVertical: 10,
    },
    formTextLinkCenter: {
        color:"grey",
        fontSize: 16,
    },
    formHead2:{
        fontSize: 20,
        color: "white",
        textAlign: "center",
        // fontWeight:"bold",
        // backgroundColor:"white",
    },
    formHead3: {
        fontSize: 20,
        backgroundColor: "white",
        color: "grey",
        textAlign: "center",
        fontWeight: 400,
        padding: 10,
        borderRadius: 10,
        width: "80%",
        marginVertical: 10,
    },
};